//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagerWithDB.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityDBEntities : DbContext
    {
        public UniversityDBEntities()
            : base("name=UniversityDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Students>().HasMany(s => s.Exames).WithRequired(e => e.Students).WillCascadeOnDelete();
            modelBuilder.Entity<Teachers>().HasMany(s => s.Exames).WithRequired(e => e.Teachers).WillCascadeOnDelete();

            modelBuilder.Entity<Faculties>().HasMany(s => s.Students).WithRequired(e => e.Faculties).WillCascadeOnDelete();
            modelBuilder.Entity<Faculties>().HasMany(s => s.Matters).WithRequired(e => e.Faculties).WillCascadeOnDelete();

            modelBuilder.Entity <Matters>().HasMany(s => s.Teachers).WithRequired(e => e.Matters).WillCascadeOnDelete();
            modelBuilder.Entity<Matters>().HasMany(s => s.Exames).WithRequired(e => e.Matters).WillCascadeOnDelete();



        }

        public virtual DbSet<Exames> Exames { get; set; }
        public virtual DbSet<Faculties> Faculties { get; set; }
        public virtual DbSet<Matters> Matters { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
