//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagerWithDB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exames
    {
        public long exame_id { get; set; }
        public string exame_code { get; set; }
        public long exame_teacher_id { get; set; }
        public long exame_student_id { get; set; }
        public System.DateTime exame_date { get; set; }
        public int exame_result { get; set; }
        public long exame_matter_id { get; set; }
    
        public virtual Matters Matters { get; set; }
        public virtual Students Students { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
