//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagerWithDB.Entity
{
    using System;
    using System.Collections.Generic;
    using UniversityManagerWithDB.Enum;
    using UniversityManagerWithDB.Helper;

    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Exames = new HashSet<Exames>();
        }
      
        

        public long student_id { get; set; }
        public string student_mat { get; set; }
        public string student_name { get; set; }
        public string student_surname { get; set; }
        public int student_age { get; set; }
        public string student_gender { get; set; }
        public System.DateTime student_date_of_enrollment { get; set; }
        public long student_faculty_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exames> Exames { get; set; }
        public virtual Faculties Faculties { get; set; }
    }
}
