//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagerWithDB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teachers()
        {
            this.Exames = new HashSet<Exames>();
        }
    
        public long teacher_id { get; set; }
        public string teacher_code { get; set; }
        public long teacher_faculty_id { get; set; }
        public long teacher_matter_id { get; set; }
        public string teacher_role { get; set; }
        public string teacher_name { get; set; }
        public string teacher_surname { get; set; }
        public string teacher_age { get; set; }
        public string teacher_gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exames> Exames { get; set; }
        public virtual Faculties Faculties { get; set; }
        public virtual Matters Matters { get; set; }
    }
}
